/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DesserteFrame.java
 *
 * Created on 26 févr. 2010, 09:40:37
 */

package org.thema.fracgis.method.network;

import java.util.TreeMap;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.DefaultXYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author gvuidel
 */
public class DesserteFrame extends javax.swing.JFrame {

    XYSeries netSerie, desserteSerie;
    double scale = 50;

    /** Creates new form DesserteFrame */
    public DesserteFrame(TreeMap<Double, Double> netCurve, TreeMap<Double, Double> desserteCurve) {
        initComponents();


        XYSeriesCollection dataset = new XYSeriesCollection();
        netSerie = new XYSeries("Network");
        for(Double x : netCurve.keySet())
            netSerie.add(x/2, netCurve.get(x));
        dataset.addSeries(netSerie);
        desserteSerie = new XYSeries("Desserte");
        for(Double x : desserteCurve.keySet())
            desserteSerie.add((double)x, scale*desserteCurve.get(x));
        dataset.addSeries(desserteSerie);
        ChartPanel chartPanel = new ChartPanel(ChartFactory.createXYLineChart("", "x", "y", dataset, PlotOrientation.VERTICAL, true, true, true));
        splitPane.setRightComponent(chartPanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        scaleSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Desserte / Accessibilité");

        scaleSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(50.0d), Double.valueOf(1.0d), null, Double.valueOf(1.0d)));
        scaleSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                scaleSpinnerStateChanged(evt);
            }
        });

        jLabel1.setText("Scale");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scaleSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scaleSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scaleSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_scaleSpinnerStateChanged
        desserteSerie.setNotify(false);
        double s = (Double)scaleSpinner.getValue();
        for(int i = 0; i < desserteSerie.getItemCount(); i++)
            desserteSerie.updateByIndex(i, desserteSerie.getY(i).doubleValue() * s / scale);

        desserteSerie.setNotify(true);

        scale = s;
    }//GEN-LAST:event_scaleSpinnerStateChanged

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner scaleSpinner;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

}
